/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package APPS;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;

/**
 *
 * @author Administrador
 */
public class Calculator extends javax.swing.JFrame {

    String SOpr="";
    boolean dot=false, sign=false;
    
    
    
    public Calculator() {
        initComponents();
        BtIg.requestFocusInWindow();
        
        BtIg.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent evnt) {
                int c = evnt.getKeyChar();
                //int c = (int)t;
                switch (c)
                {
                    case 10: goEquals(); break;//SOpr="=";
                        
                    //SetChild(SOpr);break; // suma
                    
                    case 34: SOpr="!";SetSign("^(1/2)");dot=false;break; // sin
                    case 35: SOpr="#";SetSign(SOpr);dot=false;break;// cuadrado
                    case 36: SOpr="$";SetSign(SOpr);dot=false;break; // cubo
                    case 37: SOpr="%";SetSign(SOpr);dot=false;break; // Porcentaje

                    case 42: SOpr="*";SetSign(SOpr);dot=false;break; // division
                    case 43: SOpr="+";SetSign(SOpr);dot=false;break; // suma
                    case 45: SOpr="-";SetSign(SOpr);dot=false;break; // resta
                    case 46: SetSign("."); dot=true; break; // punto
                    case 47: SOpr="/";SetSign(SOpr); dot=false;break; // division
                    

                    case 48: SetNum("0");break;
                    case 49: SetNum("1");break;
                    case 50: SetNum("2");break;
                    case 51: SetNum("3");break;
                    case 52: SetNum("4");break;
                    case 53: SetNum("5");break;
                    case 54: SetNum("6");break;
                    case 55: SetNum("7");break;
                    case 56: SetNum("8");break;
                    case 57: SetNum("9"); break;               
                    case 58: SOpr="^";SetSign(SOpr); dot=false;break;
                    default:  break;//elevacion a x
                }
            }
        }); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel3 = new javax.swing.JPanel();
    PnMain = new javax.swing.JPanel();
    TMain = new javax.swing.JTextField();
    PnChild = new javax.swing.JPanel();
    TChild = new javax.swing.JTextField();
    Pn0 = new javax.swing.JPanel();
    Bt7 = new javax.swing.JButton();
    Bt8 = new javax.swing.JButton();
    Bt9 = new javax.swing.JButton();
    BtMu = new javax.swing.JButton();
    BtDi = new javax.swing.JButton();
    BtCE = new javax.swing.JButton();
    Pn1 = new javax.swing.JPanel();
    Bt4 = new javax.swing.JButton();
    Bt5 = new javax.swing.JButton();
    Bt6 = new javax.swing.JButton();
    BtRe = new javax.swing.JButton();
    BtP = new javax.swing.JButton();
    BtPo = new javax.swing.JButton();
    Pn2 = new javax.swing.JPanel();
    Bt1 = new javax.swing.JButton();
    Bt2 = new javax.swing.JButton();
    Bt3 = new javax.swing.JButton();
    BtMa = new javax.swing.JButton();
    X2 = new javax.swing.JButton();
    X3 = new javax.swing.JButton();
    Pn3 = new javax.swing.JPanel();
    BtPu = new javax.swing.JButton();
    Bt0 = new javax.swing.JButton();
    BtBackspace = new javax.swing.JButton();
    BtPar1 = new javax.swing.JButton();
    BtPar2 = new javax.swing.JButton();
    BtIg = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setFocusCycleRoot(false);
    setMinimumSize(new java.awt.Dimension(260, 370));

    jPanel3.setBackground(new java.awt.Color(51, 51, 51));
    jPanel3.setFocusCycleRoot(true);
    jPanel3.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        jPanel3KeyPressed(evt);
      }
    });

    PnMain.setBackground(new java.awt.Color(0, 153, 255));
    PnMain.setFocusable(false);
    PnMain.setLayout(new java.awt.CardLayout());

    TMain.setEditable(false);
    TMain.setBackground(new java.awt.Color(0, 153, 255));
    TMain.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
    TMain.setForeground(new java.awt.Color(255, 255, 255));
    TMain.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    TMain.setText("0.");
    TMain.setBorder(null);
    TMain.setHighlighter(null);
    TMain.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TMainActionPerformed(evt);
      }
    });
    TMain.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusLost(java.awt.event.FocusEvent evt) {
        TMainFocusLost(evt);
      }
    });
    PnMain.add(TMain, "card2");

    PnChild.setBackground(new java.awt.Color(0, 153, 255));
    PnChild.setForeground(new java.awt.Color(255, 255, 255));
    PnChild.setFocusable(false);
    PnChild.setLayout(new java.awt.CardLayout());

    TChild.setEditable(false);
    TChild.setBackground(new java.awt.Color(0, 153, 255));
    TChild.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
    TChild.setForeground(new java.awt.Color(255, 255, 255));
    TChild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    TChild.setBorder(null);
    TChild.setFocusable(false);
    TChild.setHighlighter(null);
    PnChild.add(TChild, "card2");

    Pn0.setBackground(new java.awt.Color(51, 51, 51));
    Pn0.setFocusable(false);
    Pn0.setLayout(new java.awt.GridLayout(1, 0));

    Bt7.setBackground(new java.awt.Color(255, 255, 255));
    Bt7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    Bt7.setForeground(new java.awt.Color(204, 204, 204));
    Bt7.setText("7");
    Bt7.setBorder(null);
    Bt7.setBorderPainted(false);
    Bt7.setContentAreaFilled(false);
    Bt7.setFocusPainted(false);
    Bt7.setFocusable(false);
    Bt7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Bt7ActionPerformed(evt);
      }
    });
    Pn0.add(Bt7);

    Bt8.setBackground(new java.awt.Color(255, 255, 255));
    Bt8.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    Bt8.setForeground(new java.awt.Color(204, 204, 204));
    Bt8.setText("8");
    Bt8.setBorder(null);
    Bt8.setBorderPainted(false);
    Bt8.setContentAreaFilled(false);
    Bt8.setFocusPainted(false);
    Bt8.setFocusable(false);
    Bt8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Bt8ActionPerformed(evt);
      }
    });
    Pn0.add(Bt8);

    Bt9.setBackground(new java.awt.Color(255, 255, 255));
    Bt9.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    Bt9.setForeground(new java.awt.Color(204, 204, 204));
    Bt9.setText("9");
    Bt9.setBorder(null);
    Bt9.setBorderPainted(false);
    Bt9.setContentAreaFilled(false);
    Bt9.setFocusPainted(false);
    Bt9.setFocusable(false);
    Bt9.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Bt9ActionPerformed(evt);
      }
    });
    Pn0.add(Bt9);

    BtMu.setBackground(new java.awt.Color(255, 255, 255));
    BtMu.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    BtMu.setForeground(new java.awt.Color(204, 204, 204));
    BtMu.setText("*");
    BtMu.setBorder(null);
    BtMu.setBorderPainted(false);
    BtMu.setContentAreaFilled(false);
    BtMu.setFocusPainted(false);
    BtMu.setFocusable(false);
    BtMu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BtMuActionPerformed(evt);
      }
    });
    Pn0.add(BtMu);

    BtDi.setBackground(new java.awt.Color(255, 255, 255));
    BtDi.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    BtDi.setForeground(new java.awt.Color(204, 204, 204));
    BtDi.setText("/");
    BtDi.setBorder(null);
    BtDi.setBorderPainted(false);
    BtDi.setContentAreaFilled(false);
    BtDi.setFocusPainted(false);
    BtDi.setFocusable(false);
    BtDi.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BtDiActionPerformed(evt);
      }
    });
    Pn0.add(BtDi);

    BtCE.setBackground(new java.awt.Color(255, 255, 255));
    BtCE.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    BtCE.setForeground(new java.awt.Color(204, 204, 204));
    BtCE.setText("CE");
    BtCE.setBorder(null);
    BtCE.setBorderPainted(false);
    BtCE.setContentAreaFilled(false);
    BtCE.setFocusPainted(false);
    BtCE.setFocusable(false);
    BtCE.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        BtCEMouseClicked(evt);
      }
    });
    BtCE.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BtCEActionPerformed(evt);
      }
    });
    Pn0.add(BtCE);

    Pn1.setBackground(new java.awt.Color(51, 51, 51));
    Pn1.setFocusable(false);
    Pn1.setLayout(new java.awt.GridLayout(1, 0));

    Bt4.setBackground(new java.awt.Color(255, 255, 255));
    Bt4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    Bt4.setForeground(new java.awt.Color(204, 204, 204));
    Bt4.setText("4");
    Bt4.setBorder(null);
    Bt4.setBorderPainted(false);
    Bt4.setContentAreaFilled(false);
    Bt4.setFocusPainted(false);
    Bt4.setFocusable(false);
    Bt4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Bt4ActionPerformed(evt);
      }
    });
    Pn1.add(Bt4);

    Bt5.setBackground(new java.awt.Color(255, 255, 255));
    Bt5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    Bt5.setForeground(new java.awt.Color(204, 204, 204));
    Bt5.setText("5");
    Bt5.setBorder(null);
    Bt5.setBorderPainted(false);
    Bt5.setContentAreaFilled(false);
    Bt5.setFocusPainted(false);
    Bt5.setFocusable(false);
    Bt5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Bt5ActionPerformed(evt);
      }
    });
    Pn1.add(Bt5);

    Bt6.setBackground(new java.awt.Color(255, 255, 255));
    Bt6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    Bt6.setForeground(new java.awt.Color(204, 204, 204));
    Bt6.setText("6");
    Bt6.setBorder(null);
    Bt6.setBorderPainted(false);
    Bt6.setContentAreaFilled(false);
    Bt6.setFocusPainted(false);
    Bt6.setFocusable(false);
    Bt6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Bt6ActionPerformed(evt);
      }
    });
    Pn1.add(Bt6);

    BtRe.setBackground(new java.awt.Color(255, 255, 255));
    BtRe.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    BtRe.setForeground(new java.awt.Color(204, 204, 204));
    BtRe.setText("-");
    BtRe.setBorder(null);
    BtRe.setBorderPainted(false);
    BtRe.setContentAreaFilled(false);
    BtRe.setFocusPainted(false);
    BtRe.setFocusable(false);
    BtRe.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BtReActionPerformed(evt);
      }
    });
    Pn1.add(BtRe);

    BtP.setBackground(new java.awt.Color(255, 255, 255));
    BtP.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    BtP.setForeground(new java.awt.Color(204, 204, 204));
    BtP.setText("^");
    BtP.setBorder(null);
    BtP.setBorderPainted(false);
    BtP.setContentAreaFilled(false);
    BtP.setFocusPainted(false);
    BtP.setFocusable(false);
    BtP.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BtPActionPerformed(evt);
      }
    });
    Pn1.add(BtP);

    BtPo.setBackground(new java.awt.Color(255, 255, 255));
    BtPo.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    BtPo.setForeground(new java.awt.Color(204, 204, 204));
    BtPo.setText("√");
    BtPo.setBorder(null);
    BtPo.setBorderPainted(false);
    BtPo.setContentAreaFilled(false);
    BtPo.setFocusPainted(false);
    BtPo.setFocusable(false);
    BtPo.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        BtPoMouseClicked(evt);
      }
    });
    BtPo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BtPoActionPerformed(evt);
      }
    });
    Pn1.add(BtPo);

    Pn2.setBackground(new java.awt.Color(51, 51, 51));
    Pn2.setFocusable(false);
    Pn2.setLayout(new java.awt.GridLayout(1, 0));

    Bt1.setBackground(new java.awt.Color(255, 255, 255));
    Bt1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    Bt1.setForeground(new java.awt.Color(204, 204, 204));
    Bt1.setText("1");
    Bt1.setBorder(null);
    Bt1.setBorderPainted(false);
    Bt1.setContentAreaFilled(false);
    Bt1.setFocusPainted(false);
    Bt1.setFocusable(false);
    Bt1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Bt1ActionPerformed(evt);
      }
    });
    Pn2.add(Bt1);

    Bt2.setBackground(new java.awt.Color(255, 255, 255));
    Bt2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    Bt2.setForeground(new java.awt.Color(204, 204, 204));
    Bt2.setText("2");
    Bt2.setBorder(null);
    Bt2.setBorderPainted(false);
    Bt2.setContentAreaFilled(false);
    Bt2.setFocusPainted(false);
    Bt2.setFocusable(false);
    Bt2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Bt2ActionPerformed(evt);
      }
    });
    Pn2.add(Bt2);

    Bt3.setBackground(new java.awt.Color(255, 255, 255));
    Bt3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    Bt3.setForeground(new java.awt.Color(204, 204, 204));
    Bt3.setText("3");
    Bt3.setBorder(null);
    Bt3.setBorderPainted(false);
    Bt3.setContentAreaFilled(false);
    Bt3.setFocusPainted(false);
    Bt3.setFocusable(false);
    Bt3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Bt3ActionPerformed(evt);
      }
    });
    Pn2.add(Bt3);

    BtMa.setBackground(new java.awt.Color(255, 255, 255));
    BtMa.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    BtMa.setForeground(new java.awt.Color(204, 204, 204));
    BtMa.setText("+");
    BtMa.setBorder(null);
    BtMa.setBorderPainted(false);
    BtMa.setContentAreaFilled(false);
    BtMa.setFocusPainted(false);
    BtMa.setFocusable(false);
    BtMa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BtMaActionPerformed(evt);
      }
    });
    Pn2.add(BtMa);

    X2.setBackground(new java.awt.Color(255, 255, 255));
    X2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    X2.setForeground(new java.awt.Color(204, 204, 204));
    X2.setText("x²");
    X2.setBorder(null);
    X2.setBorderPainted(false);
    X2.setContentAreaFilled(false);
    X2.setFocusPainted(false);
    X2.setFocusable(false);
    X2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        X2MouseClicked(evt);
      }
    });
    X2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        X2ActionPerformed(evt);
      }
    });
    Pn2.add(X2);

    X3.setBackground(new java.awt.Color(255, 255, 255));
    X3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    X3.setForeground(new java.awt.Color(204, 204, 204));
    X3.setText("x³");
    X3.setBorder(null);
    X3.setBorderPainted(false);
    X3.setContentAreaFilled(false);
    X3.setFocusPainted(false);
    X3.setFocusable(false);
    X3.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        X3MouseClicked(evt);
      }
    });
    X3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        X3ActionPerformed(evt);
      }
    });
    Pn2.add(X3);

    Pn3.setBackground(new java.awt.Color(51, 51, 51));
    Pn3.setFocusable(false);
    Pn3.setLayout(new java.awt.GridLayout(1, 0));

    BtPu.setBackground(new java.awt.Color(255, 255, 255));
    BtPu.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    BtPu.setForeground(new java.awt.Color(204, 204, 204));
    BtPu.setText(".");
    BtPu.setBorder(null);
    BtPu.setBorderPainted(false);
    BtPu.setContentAreaFilled(false);
    BtPu.setFocusPainted(false);
    BtPu.setFocusable(false);
    BtPu.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BtPuActionPerformed(evt);
      }
    });
    Pn3.add(BtPu);

    Bt0.setBackground(new java.awt.Color(255, 255, 255));
    Bt0.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    Bt0.setForeground(new java.awt.Color(204, 204, 204));
    Bt0.setText("0");
    Bt0.setBorder(null);
    Bt0.setBorderPainted(false);
    Bt0.setContentAreaFilled(false);
    Bt0.setFocusPainted(false);
    Bt0.setFocusable(false);
    Bt0.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Bt0ActionPerformed(evt);
      }
    });
    Pn3.add(Bt0);

    BtBackspace.setBackground(new java.awt.Color(255, 255, 255));
    BtBackspace.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
    BtBackspace.setForeground(new java.awt.Color(204, 204, 204));
    BtBackspace.setText("←");
    BtBackspace.setBorder(null);
    BtBackspace.setBorderPainted(false);
    BtBackspace.setContentAreaFilled(false);
    BtBackspace.setFocusPainted(false);
    BtBackspace.setFocusable(false);
    BtBackspace.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        BtBackspaceMouseClicked(evt);
      }
    });
    BtBackspace.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BtBackspaceActionPerformed(evt);
      }
    });
    Pn3.add(BtBackspace);

    BtPar1.setBackground(new java.awt.Color(255, 255, 255));
    BtPar1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    BtPar1.setForeground(new java.awt.Color(204, 204, 204));
    BtPar1.setText("(");
    BtPar1.setBorder(null);
    BtPar1.setBorderPainted(false);
    BtPar1.setContentAreaFilled(false);
    BtPar1.setFocusPainted(false);
    BtPar1.setFocusable(false);
    BtPar1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        BtPar1MouseClicked(evt);
      }
    });
    BtPar1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BtPar1ActionPerformed(evt);
      }
    });
    Pn3.add(BtPar1);

    BtPar2.setBackground(new java.awt.Color(255, 255, 255));
    BtPar2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
    BtPar2.setForeground(new java.awt.Color(204, 204, 204));
    BtPar2.setText(")");
    BtPar2.setBorder(null);
    BtPar2.setBorderPainted(false);
    BtPar2.setContentAreaFilled(false);
    BtPar2.setFocusPainted(false);
    BtPar2.setFocusable(false);
    BtPar2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BtPar2ActionPerformed(evt);
      }
    });
    Pn3.add(BtPar2);

    BtIg.setBackground(new java.awt.Color(255, 255, 255));
    BtIg.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
    BtIg.setForeground(new java.awt.Color(0, 153, 255));
    BtIg.setText("=");
    BtIg.setBorder(null);
    BtIg.setBorderPainted(false);
    BtIg.setContentAreaFilled(false);
    BtIg.setFocusPainted(false);
    BtIg.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        BtIgMouseClicked(evt);
      }
    });
    BtIg.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BtIgActionPerformed(evt);
      }
    });
    BtIg.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        BtIgKeyPressed(evt);
      }
    });
    Pn3.add(BtIg);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 342, Short.MAX_VALUE)
      .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
          .addContainerGap()
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Pn1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
            .addComponent(Pn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Pn3, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
          .addContainerGap())
        .addComponent(PnMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE))
      .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(PnChild, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 516, Short.MAX_VALUE)
      .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
          .addGap(35, 35, 35)
          .addComponent(PnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addComponent(Pn0, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addComponent(Pn1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addComponent(Pn2, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addComponent(Pn3, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
          .addContainerGap()))
      .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
          .addComponent(PnChild, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 490, Short.MAX_VALUE)))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

    private void Bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt7ActionPerformed
        SetNum(Bt7.getText());
    }//GEN-LAST:event_Bt7ActionPerformed

    private void BtDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDiActionPerformed
        dot=false; SetSign(BtDi.getText());
        
    }//GEN-LAST:event_BtDiActionPerformed

    private void Bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt1ActionPerformed
        SetNum(Bt1.getText());
    }//GEN-LAST:event_Bt1ActionPerformed

    private void Bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt2ActionPerformed
        SetNum(Bt2.getText());
    }//GEN-LAST:event_Bt2ActionPerformed

    private void Bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt3ActionPerformed
        SetNum(Bt3.getText());
    }//GEN-LAST:event_Bt3ActionPerformed

    private void Bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt4ActionPerformed
        SetNum(Bt4.getText());
    }//GEN-LAST:event_Bt4ActionPerformed

    private void Bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt5ActionPerformed
        SetNum(Bt5.getText());
    }//GEN-LAST:event_Bt5ActionPerformed

    private void Bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt6ActionPerformed
        SetNum(Bt6.getText());
    }//GEN-LAST:event_Bt6ActionPerformed

    private void Bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt8ActionPerformed
        SetNum(Bt8.getText());
    }//GEN-LAST:event_Bt8ActionPerformed

    private void Bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt9ActionPerformed
        SetNum(Bt9.getText());
    }//GEN-LAST:event_Bt9ActionPerformed

    private void BtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMaActionPerformed
        dot=false; SetSign(BtMa.getText());
    }//GEN-LAST:event_BtMaActionPerformed

    private void BtReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtReActionPerformed
        dot=false;SetSign(BtRe.getText());
    }//GEN-LAST:event_BtReActionPerformed

    private void BtMuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMuActionPerformed
        dot=false;    SetSign(BtMu.getText());
        
        
    }//GEN-LAST:event_BtMuActionPerformed

    private void BtPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPActionPerformed
        dot=false;SetSign(BtP.getText());
    }//GEN-LAST:event_BtPActionPerformed

    private void X2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X2ActionPerformed
        
    }//GEN-LAST:event_X2ActionPerformed

    private void Bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt0ActionPerformed
        SetNum(Bt0.getText());
        
    }//GEN-LAST:event_Bt0ActionPerformed

    private void BtPuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPuActionPerformed
        if (false==dot)
        {
            dot=true;
            SetSign(".");
        }
    }//GEN-LAST:event_BtPuActionPerformed

    private void BtCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCEActionPerformed
        
    }//GEN-LAST:event_BtCEActionPerformed

    private void BtPoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtPoActionPerformed

    private void X3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_X3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_X3ActionPerformed

    private void BtBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBackspaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtBackspaceActionPerformed

    private void jPanel3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel3KeyPressed
        
    }//GEN-LAST:event_jPanel3KeyPressed

    private void TMainFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TMainFocusLost
       
    }//GEN-LAST:event_TMainFocusLost

    private void TMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TMainActionPerformed

    private void BtIgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIgActionPerformed
        
    }//GEN-LAST:event_BtIgActionPerformed

    private void BtIgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtIgKeyPressed
        
    }//GEN-LAST:event_BtIgKeyPressed

    private void BtIgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtIgMouseClicked
        goEquals();
    }//GEN-LAST:event_BtIgMouseClicked

    private void BtBackspaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtBackspaceMouseClicked
        
        String OP = TChild.getText();
        String substring;
        try
        {
            substring = OP.substring(0, OP.length()-1);
            TChild.setText(substring); TMain.setText("0.");
        }
        catch(Exception e){}
        
        
    }//GEN-LAST:event_BtBackspaceMouseClicked

    private void BtCEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtCEMouseClicked
        
        TMain.setText("0.");TChild.setText("");
    }//GEN-LAST:event_BtCEMouseClicked

    private void BtPoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtPoMouseClicked
        SetNum("^(1/2)");
    }//GEN-LAST:event_BtPoMouseClicked

    private void BtPar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtPar1ActionPerformed

    private void BtPar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPar2ActionPerformed
        SetPar(BtPar2.getText());
    }//GEN-LAST:event_BtPar2ActionPerformed

    private void BtPar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtPar1MouseClicked
        SetPar(BtPar1.getText());
    }//GEN-LAST:event_BtPar1MouseClicked

    private void X2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X2MouseClicked
        dot=false; SetSign("^2");
    }//GEN-LAST:event_X2MouseClicked

    private void X3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_X3MouseClicked
        dot=false; SetSign("^3");
    }//GEN-LAST:event_X3MouseClicked


    public void goEquals()
    {
      try{
        TMain.setText(String.valueOf(MathParser(TChild.getText()))); 
        dot=false;
      }
      catch(Exception e)
      {
        TMain.setText("Error!");
      }
        
    }

 
    
    public static double MathParser(final String str) {
    class Parser {
        int pos = -1, c;
        
        void eatChar() {
            c = (++pos < str.length()) ? str.charAt(pos) : -1;
        }

        void eatSpace() {
            while (Character.isWhitespace(c)) eatChar();
        }

        double parse() {
            eatChar();
            double v = parseExpression();
            if (c != -1) throw new RuntimeException("Unexpected: " + (char)c);
            return v;
        }

        // Grammar:
        // expression = term | expression `+` term | expression `-` term
        // term = factor | term `*` factor | term `/` factor | term brackets
        // factor = brackets | number | factor `^` factor
        // brackets = `(` expression `)`

        double parseExpression() {
            double v = parseTerm();
            for (;;) {
                eatSpace();
                if (c == '+') { // addition
                    eatChar();
                    v += parseTerm();
                } else if (c == '-') { // subtraction
                    eatChar();
                    v -= parseTerm();
                } else {
                    return v;
                }
            }
        }

        double parseTerm() {
            double v = parseFactor();
            for (;;) {
                eatSpace();
                if (c == '/') { // division
                    eatChar();
                    v /= parseFactor();
                } else if (c == '*' || c == '(') { // multiplication
                    if (c == '*') eatChar();
                    v *= parseFactor();
                } else {
                    return v;
                }
            }
        }

        double parseFactor() {
            double v;
            boolean negate = false;
            eatSpace();
            if (c == '+' || c == '-') { // unary plus & minus
                negate = c == '-';
                eatChar();
                eatSpace();
            }
            if (c == '(') { // brackets
                eatChar();
                v = parseExpression();
                if (c == ')') eatChar();
            } else { // numbers
                StringBuilder sb = new StringBuilder();
                while ((c >= '0' && c <= '9') || c == '.') {
                    sb.append((char)c);
                    eatChar();
                }
                if (sb.length() == 0) throw new RuntimeException("Unexpected: " + (char)c);
                v = Double.parseDouble(sb.toString());
            }
            eatSpace();
            if (c == '^') { // exponentiation
                eatChar();
                v = Math.pow(v, parseFactor());
            }
            if (negate) v = -v; // unary minus is applied after exponentiation; e.g. -3^2=-9
            return v;
        }
    }
    return new Parser().parse();
}
     public void SetNum(String NUM)
    {
        TChild.setText(TChild.getText()+NUM);
        sign=false;
    }
    
    public void SetPar(String Par)
    {
       TChild.setText(TChild.getText() + Par);
    
    }
    public void SetSign(String OP)
    {
        if (true==sign)
        { 
            
            sign=true;
            String OPR = TChild.getText();
            String substring = OPR.substring(0, OPR.length()-1);
            TChild.setText(substring+OP);
            
        }
        else
        {
            TChild.setText(TChild.getText() + OP); 
            sign=true;
        }
   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  javax.swing.JButton Bt0;
  javax.swing.JButton Bt1;
  javax.swing.JButton Bt2;
  javax.swing.JButton Bt3;
  javax.swing.JButton Bt4;
  javax.swing.JButton Bt5;
  javax.swing.JButton Bt6;
  javax.swing.JButton Bt7;
  javax.swing.JButton Bt8;
  javax.swing.JButton Bt9;
  javax.swing.JButton BtBackspace;
  javax.swing.JButton BtCE;
  javax.swing.JButton BtDi;
  javax.swing.JButton BtIg;
  javax.swing.JButton BtMa;
  javax.swing.JButton BtMu;
  javax.swing.JButton BtP;
  javax.swing.JButton BtPar1;
  javax.swing.JButton BtPar2;
  javax.swing.JButton BtPo;
  javax.swing.JButton BtPu;
  javax.swing.JButton BtRe;
  javax.swing.JPanel Pn0;
  javax.swing.JPanel Pn1;
  javax.swing.JPanel Pn2;
  javax.swing.JPanel Pn3;
  javax.swing.JPanel PnChild;
  javax.swing.JPanel PnMain;
  javax.swing.JTextField TChild;
  javax.swing.JTextField TMain;
  javax.swing.JButton X2;
  javax.swing.JButton X3;
  javax.swing.JPanel jPanel3;
  // End of variables declaration//GEN-END:variables
}
