/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


// Solo 2 Jugadores
package APPS;
    
import java.awt.Color;

public class TicTacToe extends javax.swing.JFrame {

    int player=1;
     /*Toolkit tk= getToolkit();
    Cursor CX = tk.createCustomCursor(tk.getImage(getClass().getResource("/Img/X.png")), new Point(0, 0), "blank cursor");
    Cursor CO = tk.createCustomCursor(tk.getImage(getClass().getResource("/Img/O.png")), new Point(0, 0), "blank cursor");
    */
    int X[] = new int[8];
    int O[] = new int[8];
    
    int r1   =   0   ,g1   =   153     ,b1   =   255   ; // Player  X  COLOR
    int r3   =   204   ,g3   =   0   ,b3   =   153   ; // Player  O COLOR
    
    
    int r2=0,g2=0,b2=255; // Fucsia
    
    int r4=153,g4=0,b4=255; // Rojo
    int r5=153,g5=0,b5=255; // Verde
    
    //
    public TicTacToe() {
        initComponents();
        SwitchPlayer();
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    PanelXO = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    B11 = new javax.swing.JButton();
    B12 = new javax.swing.JButton();
    B13 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    B21 = new javax.swing.JButton();
    B22 = new javax.swing.JButton();
    B23 = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    B31 = new javax.swing.JButton();
    B32 = new javax.swing.JButton();
    B33 = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    Status = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setBackground(java.awt.SystemColor.controlHighlight);

    PanelXO.setBackground(new java.awt.Color(51, 51, 51));
    PanelXO.setForeground(java.awt.SystemColor.controlHighlight);

    jPanel1.setBackground(new java.awt.Color(51, 51, 51));
    jPanel1.setForeground(java.awt.SystemColor.controlHighlight);
    jPanel1.setLayout(new java.awt.GridLayout(1, 0));

    B11.setFont(new java.awt.Font("Century Gothic", 0, 60)); // NOI18N
    B11.setForeground(new java.awt.Color(255, 102, 0));
    B11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 2));
    B11.setContentAreaFilled(false);
    B11.setFocusPainted(false);
    B11.setFocusable(false);
    B11.setRequestFocusEnabled(false);
    B11.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        B11MouseClicked(evt);
      }
    });
    B11.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B11ActionPerformed(evt);
      }
    });
    jPanel1.add(B11);

    B12.setFont(new java.awt.Font("Century Gothic", 0, 60)); // NOI18N
    B12.setForeground(new java.awt.Color(255, 255, 255));
    B12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 2));
    B12.setContentAreaFilled(false);
    B12.setFocusPainted(false);
    B12.setFocusable(false);
    B12.setRequestFocusEnabled(false);
    B12.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B12ActionPerformed(evt);
      }
    });
    jPanel1.add(B12);

    B13.setFont(new java.awt.Font("Century Gothic", 0, 60)); // NOI18N
    B13.setForeground(new java.awt.Color(255, 255, 255));
    B13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 2));
    B13.setContentAreaFilled(false);
    B13.setFocusPainted(false);
    B13.setFocusable(false);
    B13.setRequestFocusEnabled(false);
    B13.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B13ActionPerformed(evt);
      }
    });
    jPanel1.add(B13);

    jPanel2.setBackground(new java.awt.Color(51, 51, 51));
    jPanel2.setForeground(java.awt.SystemColor.controlHighlight);
    jPanel2.setLayout(new java.awt.GridLayout(1, 0));

    B21.setFont(new java.awt.Font("Century Gothic", 0, 60)); // NOI18N
    B21.setForeground(new java.awt.Color(255, 255, 255));
    B21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 2));
    B21.setContentAreaFilled(false);
    B21.setFocusPainted(false);
    B21.setFocusable(false);
    B21.setRequestFocusEnabled(false);
    B21.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B21ActionPerformed(evt);
      }
    });
    jPanel2.add(B21);

    B22.setFont(new java.awt.Font("Century Gothic", 0, 60)); // NOI18N
    B22.setForeground(new java.awt.Color(255, 255, 255));
    B22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 2));
    B22.setContentAreaFilled(false);
    B22.setFocusPainted(false);
    B22.setFocusable(false);
    B22.setRequestFocusEnabled(false);
    B22.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B22ActionPerformed(evt);
      }
    });
    jPanel2.add(B22);

    B23.setFont(new java.awt.Font("Century Gothic", 0, 60)); // NOI18N
    B23.setForeground(new java.awt.Color(255, 255, 255));
    B23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 2));
    B23.setContentAreaFilled(false);
    B23.setFocusPainted(false);
    B23.setFocusable(false);
    B23.setRequestFocusEnabled(false);
    B23.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B23ActionPerformed(evt);
      }
    });
    jPanel2.add(B23);

    jPanel3.setBackground(new java.awt.Color(51, 51, 51));
    jPanel3.setForeground(java.awt.SystemColor.controlHighlight);
    jPanel3.setLayout(new java.awt.GridLayout(1, 0));

    B31.setFont(new java.awt.Font("Century Gothic", 0, 60)); // NOI18N
    B31.setForeground(new java.awt.Color(255, 255, 255));
    B31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 2));
    B31.setContentAreaFilled(false);
    B31.setFocusPainted(false);
    B31.setFocusable(false);
    B31.setRequestFocusEnabled(false);
    B31.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B31ActionPerformed(evt);
      }
    });
    jPanel3.add(B31);

    B32.setFont(new java.awt.Font("Century Gothic", 0, 60)); // NOI18N
    B32.setForeground(new java.awt.Color(255, 255, 255));
    B32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 2));
    B32.setContentAreaFilled(false);
    B32.setFocusPainted(false);
    B32.setFocusable(false);
    B32.setRequestFocusEnabled(false);
    B32.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B32ActionPerformed(evt);
      }
    });
    jPanel3.add(B32);

    B33.setFont(new java.awt.Font("Century Gothic", 0, 60)); // NOI18N
    B33.setForeground(new java.awt.Color(255, 255, 255));
    B33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 2));
    B33.setContentAreaFilled(false);
    B33.setFocusPainted(false);
    B33.setFocusable(false);
    B33.setRequestFocusEnabled(false);
    B33.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        B33ActionPerformed(evt);
      }
    });
    jPanel3.add(B33);

    javax.swing.GroupLayout PanelXOLayout = new javax.swing.GroupLayout(PanelXO);
    PanelXO.setLayout(PanelXOLayout);
    PanelXOLayout.setHorizontalGroup(
      PanelXOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    PanelXOLayout.setVerticalGroup(
      PanelXOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PanelXOLayout.createSequentialGroup()
        .addGap(0, 0, 0)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        .addGap(0, 0, 0)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        .addGap(0, 0, 0)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        .addGap(0, 0, 0))
    );

    jPanel4.setBackground(new java.awt.Color(153, 0, 255));
    jPanel4.setForeground(new java.awt.Color(255, 255, 255));

    Status.setBackground(new java.awt.Color(51, 51, 51));
    Status.setFont(new java.awt.Font("Source Sans Pro", 0, 24)); // NOI18N
    Status.setForeground(new java.awt.Color(255, 255, 255));
    Status.setText("X");
    Status.setBorderPainted(false);
    Status.setContentAreaFilled(false);
    Status.setEnabled(false);
    Status.setFocusPainted(false);
    Status.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        StatusActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Status, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Status, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(PanelXO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(PanelXO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

    private void B11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B11ActionPerformed
        if (player==1)
        {
            B11.setText("X");   B11.setForeground(new Color(r1,g1,b1));
            X[0]+=1;  X[3]+=1;  X[6]+=1;
        }
        
        else
        {
            B11.setText("O"); B11.setForeground(new Color(r3,g3,b3));
            O[0]+=1;  O[3]+=1;  O[6]+=1;
        }
        SwitchPlayer();     GetWinner();   B11.setEnabled(false);
        
    }//GEN-LAST:event_B11ActionPerformed

    private void B12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B12ActionPerformed
         if (player==1)
        {
            B12.setText("X");   B12.setForeground(new Color(r1,g1,b1));
            X[1]+=1; X[3]+=1;
        }
                    else
        {
            B12.setText("O"); B12.setForeground(new Color(r3,g3,b3));
            O[1]+=1; O[3]+=1;
        }
        SwitchPlayer();   GetWinner();     B12.setEnabled(false);
    }//GEN-LAST:event_B12ActionPerformed

    private void B11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B11MouseClicked
        
    }//GEN-LAST:event_B11MouseClicked

    private void B13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B13ActionPerformed
        if (player==1)
        {
            B13.setText("X");   B13.setForeground(new Color(r1,g1,b1));
            X[2]+=1; X[3]+=1; X[7]+=1;
        }
                    else
        {
            B13.setText("O"); B13.setForeground(new Color(r3,g3,b3));
            O[2]+=1; O[3]+=1; O[7]+=1;
        }
        SwitchPlayer();   GetWinner();     B13.setEnabled(false);
    }//GEN-LAST:event_B13ActionPerformed

    private void B21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B21ActionPerformed
        if (player==1)
        {
            B21.setText("X");   B21.setForeground(new Color(r1,g1,b1));
            X[0]+=1;  X[4]+=1;
        }
                    else
        {
            B21.setText("O"); B21.setForeground(new Color(r3,g3,b3));
            O[0]+=1;  O[4]+=1;
        }
        SwitchPlayer();    GetWinner();    B21.setEnabled(false);
         
    }//GEN-LAST:event_B21ActionPerformed

    private void B22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B22ActionPerformed
        if (player==1)
        {
            B22.setText("X");   B22.setForeground(new Color(r1,g1,b1));
            X[1]+=1; X[4]+=1; X[6]+=1; X[7]+=1;
        }
                    else
        {
            B22.setText("O"); B22.setForeground(new Color(r3,g3,b3));
            O[1]+=1; O[4]+=1; O[6]+=1; O[7]+=1;
        }
        SwitchPlayer();   GetWinner();     B22.setEnabled(false);
    }//GEN-LAST:event_B22ActionPerformed

    private void B23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B23ActionPerformed
        if (player==1)
        {
            B23.setText("X");   B23.setForeground(new Color(r1,g1,b1));
            X[2]+=1; X[4]+=1; 
        }
                    else
        {
            B23.setText("O"); B23.setForeground(new Color(r3,g3,b3));
            O[2]+=1; O[4]+=1; 
        }
        SwitchPlayer();    GetWinner();    B23.setEnabled(false);
    }//GEN-LAST:event_B23ActionPerformed

    private void B31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B31ActionPerformed
        if (player==1)
        {
            B31.setText("X");   B31.setForeground(new Color(r1,g1,b1));
            X[0]+=1; X[5]+=1; X[7]+=1;
        }
                    else
        {
            B31.setText("O"); B31.setForeground(new Color(r3,g3,b3));
            O[0]+=1; O[5]+=1; O[7]+=1;
        }
        SwitchPlayer();    GetWinner();    B31.setEnabled(false); 
        
    }//GEN-LAST:event_B31ActionPerformed

    private void B32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B32ActionPerformed
        if (player==1)
        {
            B32.setText("X");   B32.setForeground(new Color(r1,g1,b1));
            X[1]+=1; X[5]+=1;
        }
                    else
        {
            B32.setText("O"); B32.setForeground(new Color(r3,g3,b3));
            O[1]+=1; O[5]+=1;
        }
        SwitchPlayer();    GetWinner();    B32.setEnabled(false);
    }//GEN-LAST:event_B32ActionPerformed

    private void B33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B33ActionPerformed
        if (player==1)
        {
            B33.setText("X");   B33.setForeground(new Color(r1,g1,b1));
            X[2]+=1; X[5]+=1; X[6]+=1;
        }
                    else
        {
            B33.setText("O"); B33.setForeground(new Color(r3,g3,b3));
            O[2]+=1; O[5]+=1; O[6]+=1;
        }
        SwitchPlayer();      GetWinner();  B33.setEnabled(false);
    }//GEN-LAST:event_B33ActionPerformed

    private void StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusActionPerformed
        AllEnabled(true); AllCleaned(""); SwitchPlayer();
    }//GEN-LAST:event_StatusActionPerformed

    private void SwitchPlayer()
    {
        if (player==1)
        {   player=2; Status.setText("O");
             //PanelXO.setCursor(CO); Status.setForeground(new Color(r3,g3,b3));
        }
        else
        {   player=1;Status.setText("X");
             //PanelXO.setCursor(CX); Status.setForeground(new Color(r1,g1,b1));
        }
    }
    
    private void GetWinner()
    {
        if (B11.getText().length() >0 && B12.getText().length() >0  && B13.getText().length() >0 &&
            B21.getText().length() >0 && B22.getText().length() >0  && B23.getText().length() >0 &&
            B31.getText().length() >0 && B32.getText().length() >0  && B33.getText().length() >0 )
        {
            Status.setText(" EMPATE - JUGAR DE NUEVO");
            //Status.setForeground(new Color(200,200,200));
            AllEnabled(false); 
        }
        for (int i=0; i<=7; ++i)
        {
            
            if (X[i]==3)
            {
                AllEnabled(false);
                Status.setText("X GANA - JUGAR DE NUEVO");
                //Status.setForeground(new Color(r1,g1,b1));
                 
            }
            if (O[i]==3)
            {
                AllEnabled(false);
                Status.setText("O GANA - JUGAR DE NUEVO");
                //Status.setForeground(new Color(r3,g3,b3));
                
            }
            
        }
        
    }
    
    private void AllCleaned(String e)
    {
        B11.setText(e); B12.setText(e); B13.setText(e);
        B21.setText(e); B22.setText(e); B23.setText(e);
        B31.setText(e); B32.setText(e); B33.setText(e);
        player=1;
        
        for (int i=0; i<=7; ++i)
        {X[i]=0; O[i]=0;}
    }
    private void AllEnabled(boolean e)
    {
        B11.setEnabled(e); B12.setEnabled(e); B13.setEnabled(e);
        B21.setEnabled(e); B22.setEnabled(e); B23.setEnabled(e);
        B31.setEnabled(e); B32.setEnabled(e); B33.setEnabled(e);
        Status.setEnabled(!e);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>
      
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton B11;
  private javax.swing.JButton B12;
  private javax.swing.JButton B13;
  private javax.swing.JButton B21;
  private javax.swing.JButton B22;
  private javax.swing.JButton B23;
  private javax.swing.JButton B31;
  private javax.swing.JButton B32;
  private javax.swing.JButton B33;
  private javax.swing.JPanel PanelXO;
  private javax.swing.JButton Status;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  // End of variables declaration//GEN-END:variables
}
