/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package APPS;

import APPS.Calculator;
import APPS.LUA_Editor;
import APPS.TicTacToe;


/**
 *
 * @author UTH
 */
public class Main_Menu extends javax.swing.JFrame {

    /*Toolkit tk= getToolkit();
    Cursor Uv = tk.createCustomCursor(tk.getImage(getClass().getResource("/Img/ViCur.png")), new Point(0, 0), "blank cursor");
    */
  public Main_Menu(String user) {
        initComponents();
        
        this.setTitle("User: " + user);
        /*
        PPrincipal.setCursor(Uv);
        bCal.setCursor(Uv);+
        bLua.setCursor(Uv);
        bTic.setCursor(Uv);
        */
        }

    private Main_Menu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    PPrincipal = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    bLua = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    bCal = new javax.swing.JButton();
    jPanel5 = new javax.swing.JPanel();
    bTic = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    PPrincipal.setBackground(new java.awt.Color(51, 51, 51));

    jPanel1.setBackground(new java.awt.Color(51, 51, 51));
    jPanel1.setForeground(new java.awt.Color(102, 102, 102));
    jPanel1.setLayout(new java.awt.GridLayout(1, 0));

    jPanel2.setBackground(new java.awt.Color(255, 102, 0));
    jPanel2.setForeground(new java.awt.Color(255, 255, 255));

    bLua.setBackground(new java.awt.Color(255, 204, 153));
    bLua.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
    bLua.setForeground(new java.awt.Color(255, 255, 255));
    bLua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/TX.png"))); // NOI18N
    bLua.setToolTipText("");
    bLua.setBorderPainted(false);
    bLua.setContentAreaFilled(false);
    bLua.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    bLua.setFocusPainted(false);
    bLua.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bLuaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(bLua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(bLua, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
    );

    jPanel1.add(jPanel2);

    jPanel4.setBackground(new java.awt.Color(51, 153, 255));

    bCal.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
    bCal.setForeground(new java.awt.Color(255, 255, 255));
    bCal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CLC.png"))); // NOI18N
    bCal.setToolTipText("");
    bCal.setBorderPainted(false);
    bCal.setContentAreaFilled(false);
    bCal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    bCal.setFocusPainted(false);
    bCal.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bCalActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(bCal, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(bCal, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
    );

    jPanel1.add(jPanel4);

    jPanel5.setBackground(new java.awt.Color(153, 0, 255));

    bTic.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
    bTic.setForeground(new java.awt.Color(255, 255, 255));
    bTic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/TTT2.png"))); // NOI18N
    bTic.setToolTipText("");
    bTic.setBorderPainted(false);
    bTic.setContentAreaFilled(false);
    bTic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    bTic.setFocusPainted(false);
    bTic.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bTicActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(bTic, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(bTic, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
    );

    jPanel1.add(jPanel5);

    javax.swing.GroupLayout PPrincipalLayout = new javax.swing.GroupLayout(PPrincipal);
    PPrincipal.setLayout(PPrincipalLayout);
    PPrincipalLayout.setHorizontalGroup(
      PPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PPrincipalLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    PPrincipalLayout.setVerticalGroup(
      PPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PPrincipalLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(PPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(PPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

    private void bLuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLuaActionPerformed
        jButton1();
    }//GEN-LAST:event_bLuaActionPerformed

    private void bCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalActionPerformed
        jButton2();
    }//GEN-LAST:event_bCalActionPerformed

    private void bTicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTicActionPerformed
        jButton3();
    }//GEN-LAST:event_bTicActionPerformed
private void jButton1()
{
    LUA_Editor open = new LUA_Editor();
    open.setVisible(true);
}
   private void jButton2()
{
    Calculator open = new Calculator();
    open.setVisible(true);
}
   
      private void jButton3()
{
    TicTacToe open = new TicTacToe();
    open.setVisible(true);
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main_Menu().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel PPrincipal;
  private javax.swing.JButton bCal;
  private javax.swing.JButton bLua;
  private javax.swing.JButton bTic;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  // End of variables declaration//GEN-END:variables
}
