/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LOG;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.io.UnsupportedEncodingException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author renec
 */
public class PASSCHANGE extends javax.swing.JFrame {

    /** Creates new form LOGIN */
    int Tr=0;
    String CrntPass,CrntUser;
    public PASSCHANGE(String user, String pass) {
        initComponents();
        ChangePass.requestFocus();
        NewPass2.setEchoChar((char)0);
        NewPass1.setEchoChar((char)0);
        CurrentPass.setEchoChar((char)0);
        CrntPass=pass;
        CrntUser=user;
    }

    private PASSCHANGE() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        b2Img = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        NewPass1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        bPassImg = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        NewPass2 = new javax.swing.JPasswordField();
        pSignIn = new javax.swing.JPanel();
        ChangePass = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        bPassImg1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        CurrentPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NEW PASSWORD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        b2Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/KeyGray.png"))); // NOI18N
        b2Img.setBorder(null);
        b2Img.setBorderPainted(false);
        b2Img.setContentAreaFilled(false);
        b2Img.setFocusPainted(false);
        b2Img.setFocusable(false);
        b2Img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ImgActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        NewPass1.setBackground(new java.awt.Color(51, 51, 51));
        NewPass1.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        NewPass1.setForeground(new java.awt.Color(153, 153, 153));
        NewPass1.setText("New Password");
        NewPass1.setBorder(null);
        NewPass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NewPass1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewPass1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(b2Img)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NewPass1)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2Img)
                    .addComponent(NewPass1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        bPassImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/KeyGray.png"))); // NOI18N
        bPassImg.setBorder(null);
        bPassImg.setBorderPainted(false);
        bPassImg.setContentAreaFilled(false);
        bPassImg.setFocusPainted(false);
        bPassImg.setFocusable(false);

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));

        NewPass2.setBackground(new java.awt.Color(51, 51, 51));
        NewPass2.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        NewPass2.setForeground(new java.awt.Color(153, 153, 153));
        NewPass2.setText("New Password");
        NewPass2.setBorder(null);
        NewPass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NewPass2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NewPass2FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(bPassImg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NewPass2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bPassImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewPass2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pSignIn.setBackground(new java.awt.Color(153, 0, 255));

        ChangePass.setBackground(new java.awt.Color(153, 0, 255));
        ChangePass.setFont(new java.awt.Font("Source Sans Pro", 0, 24)); // NOI18N
        ChangePass.setForeground(new java.awt.Color(255, 255, 255));
        ChangePass.setText("CHANGE");
        ChangePass.setBorder(null);
        ChangePass.setContentAreaFilled(false);
        ChangePass.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ChangePass.setFocusCycleRoot(true);
        ChangePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChangePassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChangePassMouseExited(evt);
            }
        });
        ChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSignInLayout = new javax.swing.GroupLayout(pSignIn);
        pSignIn.setLayout(pSignInLayout);
        pSignInLayout.setHorizontalGroup(
            pSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChangePass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pSignInLayout.setVerticalGroup(
            pSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChangePass, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        bPassImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/KeyGray.png"))); // NOI18N
        bPassImg1.setBorder(null);
        bPassImg1.setBorderPainted(false);
        bPassImg1.setContentAreaFilled(false);
        bPassImg1.setFocusPainted(false);
        bPassImg1.setFocusable(false);
        bPassImg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPassImg1ActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));

        CurrentPass.setBackground(new java.awt.Color(51, 51, 51));
        CurrentPass.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        CurrentPass.setForeground(new java.awt.Color(153, 153, 153));
        CurrentPass.setText("Current Password");
        CurrentPass.setToolTipText("");
        CurrentPass.setBorder(null);
        CurrentPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CurrentPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CurrentPassFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(bPassImg1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CurrentPass)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bPassImg1)
                    .addComponent(CurrentPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(pSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b2ImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ImgActionPerformed

    private void ChangePassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePassMouseEntered
        ChangePass.setForeground (new Color (153,0,255));
        pSignIn.setBackground (new Color (255,255,255));
    }//GEN-LAST:event_ChangePassMouseEntered

    private void ChangePassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePassMouseExited
        ChangePass.setForeground (new Color (255,255,255));
        pSignIn.setBackground (new Color (153,0,255));
    }//GEN-LAST:event_ChangePassMouseExited

    private void ChangePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePassMouseClicked
        
        
        if (CrntPass == null ? CurrentPass.getText() == null : CrntPass.equals(CurrentPass.getText()))
        {
            if (NewPass1.getText().equals(NewPass2.getText()))
            {
              try {
                ProjLocation Dir= new ProjLocation();
                File inCN = new File( Dir.Dir() + "UsrData/PassWordData.txt");
                File NewCN = new File(NewPass1.getText());
                try (PrintStream out = new PrintStream(new FileOutputStream(inCN.toString())))
                {
                  out.print(NewCN.toString());
                  JOptionPane.showMessageDialog(null, "Password Changed");
                  LOGIN open = new LOGIN(CrntUser,NewPass1.getText()); open.setVisible(true);
                  this.dispose();
                }
                catch(Exception e) {Desktop d=Desktop.getDesktop();
                try {
                  d.browse(new URI("https://www.stackoverflow.com/search?q="+e.getMessage()));
                } catch (URISyntaxException | IOException ex) {
                  Logger.getLogger(PASSCHANGE.class.getName()).log(Level.SEVERE, null, ex);
                }}
                
              }
              catch(UnsupportedEncodingException ex) {Logger.getLogger(PASSCHANGE.class.getName()).log(Level.SEVERE, null, ex);
}
                               
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Passwords doesn't match");            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Wrong Password - Try again");        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_ChangePassMouseClicked

    private void NewPass2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewPass2FocusGained
        if (NewPass2.getText().equals("New Password"))
        {
            NewPass2.setText(""); NewPass2.setEchoChar('•');
            NewPass2.setForeground( new Color(255,255,255));
            bPassImg.setIcon(new ImageIcon(getClass().getResource("/Img/KeyPurple.png")));
        }
    }//GEN-LAST:event_NewPass2FocusGained

    private void NewPass2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewPass2FocusLost
        if (NewPass2.getText().equals("")||NewPass2.getText().equals(" "))
        {
            NewPass2.setText("New Password"); NewPass2.setEchoChar((char)0);
            NewPass2.setForeground( new Color(153,153,153));
            b2Img.setIcon(new ImageIcon(getClass().getResource("/Img/KeyGray.png")));
        }
    }//GEN-LAST:event_NewPass2FocusLost

    private void ChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePassActionPerformed
        
    }//GEN-LAST:event_ChangePassActionPerformed

    private void bPassImg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPassImg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPassImg1ActionPerformed

    private void NewPass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewPass1FocusGained
        if (NewPass1.getText().equals("New Password"))
        {
            NewPass1.setText(""); NewPass1.setEchoChar('•');
            NewPass1.setForeground( new Color(255,255,255));
            b2Img.setIcon(new ImageIcon(getClass().getResource("/Img/KeyPurple.png")));
        }
    }//GEN-LAST:event_NewPass1FocusGained

    private void NewPass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NewPass1FocusLost
        if (NewPass1.getText().equals("")||NewPass1.getText().equals(" "))
        {
            NewPass1.setText("New Password"); NewPass1.setEchoChar((char)0);
            NewPass1.setForeground( new Color(153,153,153));
            b2Img.setIcon(new ImageIcon(getClass().getResource("/Img/KeyGray.png")));
        }
    }//GEN-LAST:event_NewPass1FocusLost

    private void CurrentPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CurrentPassFocusGained
        if (CurrentPass.getText().equals("Current Password"))
        {
            CurrentPass.setText(""); CurrentPass.setEchoChar('•');
            CurrentPass.setForeground( new Color(255,255,255));
            bPassImg1.setIcon(new ImageIcon(getClass().getResource("/Img/KeyPurple.png")));
        }
    }//GEN-LAST:event_CurrentPassFocusGained

    private void CurrentPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CurrentPassFocusLost
        if (CurrentPass.getText().equals("")||CurrentPass.getText().equals(""))
        {
            CurrentPass.setText("Current Password"); CurrentPass.setEchoChar((char)0);
            CurrentPass.setForeground( new Color(153,153,153));
            bPassImg1.setIcon(new ImageIcon(getClass().getResource("/Img/KeyGray.png")));
        }
    }//GEN-LAST:event_CurrentPassFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PASSCHANGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      //</editor-fold>
      //</editor-fold>
      
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PASSCHANGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangePass;
    private javax.swing.JPasswordField CurrentPass;
    private javax.swing.JPasswordField NewPass1;
    private javax.swing.JPasswordField NewPass2;
    private javax.swing.JButton b2Img;
    private javax.swing.JButton bPassImg;
    private javax.swing.JButton bPassImg1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel pSignIn;
    // End of variables declaration//GEN-END:variables
}
