/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LOG;

import APPS.Main_Menu;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author renec
 */
public class LOGIN extends javax.swing.JFrame {

    /** Creates new form LOGIN */
    int Tr=0;
    String usr, pas;
    Toolkit tk= getToolkit();
    String nPass="";
    public LOGIN(String nUser, String nPass) {
        initComponents();
        bSignIn.requestFocus();
        tPass.setEchoChar((char)0);
        pas=nPass; usr=nUser;
    }

    private LOGIN() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bUserImg = new javax.swing.JButton();
        tUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        bPassImg = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        tPass = new javax.swing.JPasswordField();
        pSignIn = new javax.swing.JPanel();
        bSignIn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        bKeyboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN IN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        bUserImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/MaleGray.png"))); // NOI18N
        bUserImg.setBorder(null);
        bUserImg.setBorderPainted(false);
        bUserImg.setContentAreaFilled(false);
        bUserImg.setFocusPainted(false);
        bUserImg.setFocusable(false);
        bUserImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUserImgActionPerformed(evt);
            }
        });

        tUser.setBackground(jPanel5.getBackground());
        tUser.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        tUser.setForeground(new java.awt.Color(153, 153, 153));
        tUser.setText("User");
        tUser.setBorder(null);
        tUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tUserFocusLost(evt);
            }
        });
        tUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUserActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(bUserImg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tUser)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bUserImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        bPassImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/KeyGray.png"))); // NOI18N
        bPassImg.setBorder(null);
        bPassImg.setBorderPainted(false);
        bPassImg.setContentAreaFilled(false);
        bPassImg.setFocusPainted(false);
        bPassImg.setFocusable(false);

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));

        tPass.setBackground(new java.awt.Color(51, 51, 51));
        tPass.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        tPass.setForeground(new java.awt.Color(153, 153, 153));
        tPass.setText("Password");
        tPass.setBorder(null);
        tPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tPassFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(bPassImg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tPass)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bPassImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pSignIn.setBackground(new java.awt.Color(153, 0, 255));

        bSignIn.setBackground(new java.awt.Color(153, 0, 255));
        bSignIn.setFont(new java.awt.Font("Source Sans Pro", 0, 24)); // NOI18N
        bSignIn.setForeground(new java.awt.Color(255, 255, 255));
        bSignIn.setText("SIGN IN");
        bSignIn.setBorder(null);
        bSignIn.setContentAreaFilled(false);
        bSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bSignIn.setFocusCycleRoot(true);
        bSignIn.setFocusPainted(false);
        bSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSignInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bSignInMouseExited(evt);
            }
        });
        bSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSignInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSignInLayout = new javax.swing.GroupLayout(pSignIn);
        pSignIn.setLayout(pSignInLayout);
        pSignInLayout.setHorizontalGroup(
            pSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pSignInLayout.setVerticalGroup(
            pSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Change my password");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Don't have an account?");

        jLabel4.setFont(new java.awt.Font("Source Sans Pro", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 102, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Create one now.");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));

        bKeyboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Keyboard.png"))); // NOI18N
        bKeyboard.setBorderPainted(false);
        bKeyboard.setContentAreaFilled(false);
        bKeyboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bKeyboard.setFocusPainted(false);
        bKeyboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bKeyboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bKeyboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bKeyboardMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bKeyboardMouseReleased(evt);
            }
        });
        bKeyboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeyboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addComponent(bKeyboard)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(pSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bKeyboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserActionPerformed

    private void bKeyboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeyboardActionPerformed
        try {
            Runtime.getRuntime().exec("cmd /c C:\\Windows\\System32\\osk.exe");
        } catch (IOException ex) {
            Logger.getLogger(LOGIN.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            String[] command = new String[]{"/bin/sh", "-c", "xvkbd -no-repeat >/dev/null 2>&1 &"};
            Process p = Runtime.getRuntime().exec(command);
        } catch (IOException ex) {
            Logger.getLogger(LOGIN.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bKeyboardActionPerformed
    private void tUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tUserFocusGained
        if (tUser.getText().equals("User"))
        {
            tUser.setText("");
            bUserImg.setIcon(new ImageIcon(getClass().getResource("/Img/MalePurple.png")));
        }
    }//GEN-LAST:event_tUserFocusGained

    private void bUserImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUserImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bUserImgActionPerformed

    private void tUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tUserFocusLost
        if (tUser.getText().equals("")||tUser.getText().equals(" "))
        {
            tUser.setText("User");
            bUserImg.setIcon(new ImageIcon(getClass().getResource("/Img/MaleGray.png")));
        }
    }//GEN-LAST:event_tUserFocusLost

    private void bKeyboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKeyboardMouseEntered
        bKeyboard.setIcon(new ImageIcon(getClass().getResource("/Img/KeyboardWhite.png")));
    }//GEN-LAST:event_bKeyboardMouseEntered

    private void bKeyboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKeyboardMousePressed
        bKeyboard.setIcon(new ImageIcon(getClass().getResource("/Img/KeyboardPurple.png")));
    }//GEN-LAST:event_bKeyboardMousePressed

    private void bKeyboardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKeyboardMouseReleased
        bKeyboard.setIcon(new ImageIcon(getClass().getResource("/Img/KeyboardWhite.png")));
    }//GEN-LAST:event_bKeyboardMouseReleased

    private void bKeyboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKeyboardMouseExited
        bKeyboard.setIcon(new ImageIcon(getClass().getResource("/Img/Keyboard.png")));
    }//GEN-LAST:event_bKeyboardMouseExited

    private void bSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSignInMouseEntered
        bSignIn.setForeground (new Color (153,0,255));
        pSignIn.setBackground (new Color (255,255,255));
    }//GEN-LAST:event_bSignInMouseEntered

    private void bSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSignInMouseExited
        bSignIn.setForeground (new Color (255,255,255));
        pSignIn.setBackground (new Color (153,0,255));
    }//GEN-LAST:event_bSignInMouseExited

    private void bSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSignInMouseClicked
    
// TODO add your handling code here:
    }//GEN-LAST:event_bSignInMouseClicked

    private void tPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPassFocusGained
        if (tPass.getText().equals("Password"))
        {
            tPass.setText(""); tPass.setEchoChar('•');
            bPassImg.setIcon(new ImageIcon(getClass().getResource("/Img/KeyPurple.png")));
            
        }
    }//GEN-LAST:event_tPassFocusGained

    private void tPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPassFocusLost
        if (tPass.getText().equals("")||tPass.getText().equals(" "))
        {
            tPass.setText("Password"); tPass.setEchoChar((char)0);
            bPassImg.setIcon(new ImageIcon(getClass().getResource("/Img/KeyGray.png")));
        }
    }//GEN-LAST:event_tPassFocusLost

    private void bSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSignInActionPerformed
        if (!(tUser.getText().length() == 0) &&   !(tPass.getText().length() == 0))
        {
            if (usr.equals(tUser.getText())&& pas.equals(tPass.getText()))
            {
                Main_Menu open = new Main_Menu(usr); open.setVisible(true); this.dispose();
            }
            else{
                
                if (tUser.getText().equals("User") || tUser.getText().equals(""))
                {JOptionPane.showMessageDialog(null, "Incomplete data - User");return;}
                else
                {if (!usr.equals(tUser.getText()))
                {JOptionPane.showMessageDialog(null, "Wrong User - Try again");return;}}
                
                if (tPass.getText().equals("Password") || tPass.getText().equals(""))
                {JOptionPane.showMessageDialog(null, "Incomplete data - Password");return;}
                else{
                if (!pas.equals(tPass.getText()))
                {JOptionPane.showMessageDialog(null, "Wrong Password - Try again");return;}}
                
                ++Tr; 
            }
        }
        else
        {
            if (tUser.getText().equals("User"))
            {JOptionPane.showMessageDialog(null, "Incomplete data - User");}
            if (tPass.getText().equals("Password"))
            {JOptionPane.showMessageDialog(null, "Incomplete data - Password");}
        }
    }//GEN-LAST:event_bSignInActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        PASSCHANGE open = new PASSCHANGE(usr,pas); open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKeyboard;
    private javax.swing.JButton bPassImg;
    private javax.swing.JButton bSignIn;
    private javax.swing.JButton bUserImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel pSignIn;
    private javax.swing.JPasswordField tPass;
    private javax.swing.JTextField tUser;
    // End of variables declaration//GEN-END:variables
}
